### ISSUE TITLE
python-libmaas does not support moving vlans

### ISSUE THREAD

**Issue by envasquez** [maas/python-libmaas#174]
It is not possible to update fabrics.vlans or change the vlan.fabric as these are read-only attributes.
API says support is there:
https://bugs.launchpad.net/maas/+bug/1704501

The maas server supports moving vlans thru the cli:
http://paste.ubuntu.com/p/63GqJf88mb/

Would like a viable way to do this thru the libray

**Comment by roaksoax** [comment]
Can you please provide a snippet of how you were trying to move the vlan and the errors you got?

**Comment by roaksoax** [comment]
Also, could you please provide the expected mechanism to update it/change it?
