### ISSUE TITLE
Machine.commission testing_scripts parameter not consistent with API documentation

### ISSUE THREAD

**Issue by gubouvier** [maas/python-libmaas#185]
As per API documentation (https://docs.maas.io/2.4/en/api), the testing_scripts parameter should be : "A comma seperated list of testing script names and tags to be run. By default all tests tagged 'commissioning' will be run. Set to 'none' to disable running tests."

In the Machine class commission function, it mentions "Passing empty list will disable running any testing scripts during commissioning."

Also the parameter validation at the begining of the function does it
```
if testing_scripts is not None:
	if len(testing_scripts) == 0:
		params["testing_scripts"] = ""
	else:
		params["testing_scripts"] = ",".join(testing_scripts)
```

However, when MaaS receives an empty 'testing_scripts' parameter, it does return HTTP 400 with this error:
{"testing_scripts": ["Select a valid choice.  is not one of the available choices."], "__all__": ["Commission is not available because of the current state of the node."]}

The workaround I found was to pass ```testing_scripts=["none"]``` to the commission function.

**Comment by blakerouse** [comment]
Fixed in #195.
