### ISSUE TITLE
PyPI version 0.6.1 does not match GH version 0.6.1

### ISSUE THREAD

**Issue by txmoose** [maas/python-libmaas#194]
Howdy!

The package version in PyPI and GitHub are not the same, but have the same version number (0.6.1).  See the following:

```
$ python3 -m virtualenv pypi
$ python3 -m virtualenv github
$ pypi/bin/pip install -q python-libmaas
$ github/bin/pip install -q git+https://github.com/maas/python-libmaas.git@585a85ac9b93156e074702de05c56761ed09b9b9
$ diff pypi/lib/python3.7/site-packages/maas/client/__init__.py github/lib/python3.7/site-packages/maas/client/__init__.py
8c8
< from .utils.async import asynchronous
---
> from .utils.maas_async import asynchronous
```

I would propose a version number bump - 0.6.1 -> 0.6.2, perhaps - to account for this.

Thanks!

**Comment by roaksoax** [comment]
Hi There,

The GH revision you are downloading (585a85ac9b93156e074702de05c56761ed09b9b9) for comparison is *not* 0.6.1. That revision is latest master.

0.6.1 is a672faf2c9c433575b683f6fbf5f783ed2f479a1

We will release 0.6.2 as soon as that's ready!

Thanks!

**Comment by roaksoax** [comment]
Closing this bug.
