### ISSUE TITLE
Can't add tags to nodes/machines

### ISSUE THREAD

**Issue by juan-vg** [maas/python-libmaas#204]
## Environment
python-libmaas==0.6.1
Python 3.6.7

## Problem
The node/machine attribute `tags` is readonly. It doesn't allow to manipulate those tags.

## Proposed solution
The endpoint `api/2.0/tags/<TAG>/?op=update_nodes` allows to add/remove tags to/from nodes

**Comment by JeremyMordkoff** [comment]
bump
I need this too. I want to create a script that can set the interface config per the needs of a model and then set a tag to mark it as ready for deployment by that particular model
