### ISSUE TITLE
machines.list() is incredibly slow

### ISSUE THREAD

**Issue by Ehekatl** [maas/python-libmaas#208]
On maas 2.5.2 It took 40 seconds to load on localhost (for about 100 nodes)

The performance is way too bad, I can imagine the total nodes could easily go beyond 10k in production. That basically means load forever.

The query should support something like filter by ip, and the backend service need some improvement as well

**Comment by blakerouse** [comment]
This is actually an issue with the MAAS API, not with the library directly. It's an ongoing conversation on how to improve the performance of this API and it will be implemented in this library at that time.

**Comment by Ehekatl** [comment]
ya no doubt it's a backend issue

but the lib could support some query parameter to lower the cost?

**Comment by r00ta** [comment]
Already tracked in our bug tracker as https://bugs.launchpad.net/maas/+bug/1880966
