### ISSUE TITLE
Cannot move VLAN to the Default Fabric

### ISSUE THREAD

**Issue by JeremyMordkoff** [maas/python-libmaas#212]
maas 2.3.5 

When a new machine is discovered, my primary 10 gbps interface is assigned to the wrong fabric so when I go to assign a vlan to it, it fails, I assume because the VLAN is part of a different fabric. If I fix the fabric using the GUI and then run my script, it works fine. 

So how can I set the fabric in my script? 

[set_vlans.txt](https://github.com/maas/python-libmaas/files/3143085/set_vlans.txt)

**Comment by newell** [comment]
I have verified that this is the case and we are taking a look into the matter.  Thanks for reporting this.

**Comment by blakerouse** [comment]
So the actually issue is that changing a VLAN fabric to the default fabric does not work. Changing it to the a none default fabric, does work. Has to do with the default fabric having the ID of 0.
