### ISSUE TITLE
[Request] Release 0.6.3

### ISSUE THREAD

**Issue by juan-vg** [maas/python-libmaas#223]
Hello,

Considering the last (huge & awesome) changes I would like to see a new release (0.6.3) on [PyPI](https://pypi.org/project/python-libmaas/).

Thanks for the effort BTW!

Best regards

**Comment by juan-vg** [comment]
Don't forget to update the version in 'setup.py' file (it's still 0.6.1)

**Comment by juan-vg** [comment]
I've found some bugs that must be corrected before. I will reopen it then

**Comment by blakerouse** [comment]
Released:

https://pypi.org/project/python-libmaas/0.6.3/
