### ISSUE TITLE
interface link delete is broken - dictionary modified during loop over items()

### ISSUE THREAD

**Issue by tatuylonen** [maas/python-libmaas#242]
There appears to be a bug in ``maas/client/bones/__init__.py`` line 304 (in ``ActionAPI.__call__``), which has:
```
  for key, value in data.items():
      if key.startswith("_"):
          data[key[1:]] = data.pop(key)
```
This modifies the dictionary ``data`` during the loop, which throws an error while trying to delete a link (IP address) from a network interface on a machine's interfaces list.

Another loop on line 299 in the same function already uses ``for ... in data.copy().items()``, which is one way to fix this.  The same fix could be used here by adding ``.copy()`` to the second loop.  Alternatively, I might propose using ``tuple(data.items())`` in the loop.   I tried adding ``tuple(...)`` and the error went away.

**Comment by sparkiegeek** [comment]
Fixed in #247
