### ISSUE TITLE
Machines/Machine classes need to be updated to use new terminology

### ISSUE THREAD

**Issue by brendan-donegan** [maas/python-libmaas#25]
I'm not sure whether it's planned to support both 1.0 and 2.0 API versions, but it looks like several of the APIs need updating to use 2.0 terminology. For example the Machines class provides an 'acquire' class method but in 2.0 it's referred to as 'allocate'. Again, the Machine class provides a method 'start' but this is referred to as 'deploy' in 2.0

**Comment by allenap** [comment]
This library only targets 2.0+ API versions, so you're right that the terminology needs updating.

**Comment by brendan-donegan** [comment]
This was fixed
