### ISSUE TITLE
Makefile not working in master

### ISSUE THREAD

**Issue by erik78se** [maas/python-libmaas#256]
https://github.com/maas/python-libmaas/blob/1f6378049e8f3cc8a43941ae0e4a02b5f8afc3c7/doc/index.md

Failure....
```
erik@node:~/allcode/python-libmaas$ make
if [ -x /usr/bin/snap ]; then sudo snap install --classic snapcraft; fi
[sudo] password for erik: 
```

This code breaks the make since it states that if the file is executable, then install.

It should be the other way around...

```
# ---
install-dependencies:
        if [ -x /usr/bin/snap ]; then sudo snap install --classic snapcraft; fi
# ---
```

**Comment by r00ta** [comment]
Not a bug
