### ISSUE TITLE
maas login got an unexpected keyword argument 'verify_ssl'

### ISSUE THREAD

**Issue by erik78se** [maas/python-libmaas#257]
When entering an URL that might not be the right, the error that is thrown is really not helpful.

This is what it looks like....
```
(python-libmaas) erik@dcv-engineering:~/allcode/python-libmaas$ maas login
URL: https://maas.example.com/MAAS
Username: erik
Password: 
Error: __init__() got an unexpected keyword argument 'verify_ssl'

```

Something is going wrong here.

**Comment by erik78se** [comment]
I noticed that the aiohttp version == 4.0.01a1 dont support the verify_ssl=False anymore...


# So I installed the 3.7.2
 pip3 install aiohttp==3.7.2

# and removed the 4.0.0a1 version ....
Installing collected packages: aiohttp
  Attempting uninstall: aiohttp
    Found existing installation: aiohttp 4.0.0a1
    Uninstalling aiohttp-4.0.0a1:
      Successfully uninstalled aiohttp-4.0.0a1
Successfully installed aiohttp-3.7.2

# Then, it worked
(venv) erik@dcv-engineering:~/allcode/python-libmaas$ bin/maas login
URL: http://maas.rnd.scania.com:5240/MAAS/api/2.0
Username: erik
Password: 
Congratulations! You are logged in to the MAAS server at http://maas.rnd.scania.com:5240/MAAS/api/2.0/ with the profile name erik.

For help with the available commands, try:

  maas help

(venv) sssler@dcv-engineering:~/allcode/python-libmaas$

**Comment by r00ta** [comment]
Not a bug
