### ISSUE TITLE
Method to delete SSH keys?

### ISSUE THREAD

**Issue by A0lson** [maas/python-libmaas#262]
Is there a way to delete SSHKeys with the libmaas Python library?

For a client, I see methods to create/get/list  ssh_keys, but not a way to delete existing ones...

**Comment by A0lson** [comment]
Sorry, didn't see PR #260  before, I'm also interested in seeing it merged!

**Comment by r00ta** [comment]
https://github.com/maas/python-libmaas/pull/260 has been merged
