### ISSUE TITLE
[featurerequest] Ability to query power information

### ISSUE THREAD

**Issue by seanhoughton** [maas/python-libmaas#81]
It would be really useful to be able to use the "op=power_parameters" machine query to get IPMI information. Something like...

`c.machines.get('machineid').power_parameters`

I looked through the code to see if I could add it myself but used up my self-imposed timebox :) The code uses some abstractions that make it pretty difficult to follow for someone new to the project.

**Comment by seanhoughton** [comment]
I see that there's a test case for this, so it appears that it's possible, but I can't figure out the syntax to use in real code.

```
def test__Machines_power_parameters(self):
        session = bones.SessionAPI(self.description, ("a", "b", "c"))
        action = session.Machines.power_parameters
        self.assertThat(action, MatchesStructure.byEquality(
            name="power_parameters", fullname="Machines.power_parameters",
            method="GET", handler=session.Machines, is_restful=False,
            op="power_parameters",
        ))
```

**Comment by seanhoughton** [comment]
Ok, after a more hours than I would like to admit, I've figured out the required incantation, thanks to the unit tests:

```
    for machine in await origin.Machines.read():
        if machine.status_name == 'New':
            get_power = origin.session.Machine.power_parameters.bind(system_id=machine.system_id)
            power = await get_power.call()
            logging.info('%s - %s %s', machine.hostname, machine.ip_addresses, power.data)
```

It would really be nice if this was part of the simple api.

**Comment by brendan-donegan** [comment]
Hi Sean,

Actually the Machines endpoint has a 'power_parameters' method - the branch I attached exposes this as a method on the Machines class
