### ISSUE TITLE
machines.get_power_parameters should not be top level on machines

### ISSUE THREAD

**Issue by blakerouse** [maas/python-libmaas#84]
We are creating this library to make it easy for people to use the MAAS API. Placing this operation at the top level doesn't seem like the best idea or present a clean library for people to use. I would think something like this would be better:

```
machine = await client.machines.get("asdasd")
power_parameters = await machine.get_power_parameters()
```

Getting the power parameters for all the nodes at the same time seems like a weird operation to want. If we want to have the top level one as well that is fine, but I think the main way and the documented way should really be, what is above.

**Comment by allenap** [comment]
Perhaps we should expose BMCs instead of the power parameters directly?

**Comment by blakerouse** [comment]
I would actually like this but the API at the moment does not allow this and would be some work to enable a BMC endpoint in the API. I think it would be best to add a `get_power_parameters` method to the machine object, and rename the other endpoint to `machines.get_power_parameters_for`.

**Comment by brendan-donegan** [comment]
I don't think get_power_parameters_for makes any sense in the context of getting power params for all machines, it reads like 'get power parameters for nothing'

I think users will understand that in the context of 'machines' rather than a 'machine', it gets all power parameters (or the specified ones)

**Comment by blakerouse** [comment]
What is weird about the `get_power_parameters` on `machines` is that it doesn't return a `Machine` object. It returns a list of dictionaries that have no correlation to the machine that those parameters apply to.

The `get_power_parameters_for` is the symbol that you should provide a list of machines you want the power parameters. I think its wierd in this case that our API returns all for all machines. I think this API should return an empty list unless system_id are given.

**Comment by brendan-donegan** [comment]
But then there's no way to get all of the power parameters, should you wish
to do that - you would have to iterate over each machine, or get all the
machines then construct a list of system_ids and call
get_power_parameters_for with that

**Comment by blakerouse** [comment]
Why would you ever want all the power_parameters with no context of what machines you want them for? Seems weird to say just give me all the power_parameters? Why for what?

I am also not saying that `get_power_parameters_for` is not useful, just is this the correct way to do it.

**Comment by brendan-donegan** [comment]
>> client.machines.get_power_parameters()
>> client.machines.get_power_parameters(system_ids=[...])

vs.

>> client.machines.get_power_parameters_for()
>> client.machines.get_power_parameters_for(system_ids=[])

To me, the first one is *slightly* less clear when a subset of the power
params, but still clear enough and much clearer when getting all of them.
The second is slightly more clear for the subset, but actively confusing
when we intend to get them all.

I do agree that getting a subset is going to be the more common usage
though.

Another proposal:

>> client.machines.get_all_power_parameters() # takes no arguments
>> client.machines.get_power_parameters_for(system_ids=[...]) # takes 1
required argument

Clear in both cases, but slightly less elegant (not that there's anything
elegant about any of this)

**Comment by blakerouse** [comment]
I like the final proposal the best as its explanatory, but would like to get @allenap opinion on the matter as well.

Also what do these calls return? Just dictionaries? Do each reference a system_id some how? Should we expose the result as a first class object?

**Comment by blakerouse** [comment]
The `load()` and `loaded` is documented in the library specification that we designed. Don't know if we are close to having that implemented yet or not.

**Comment by brendan-donegan** [comment]
Actually, can the Machine object be keys? I would have thought they are mutable?

**Comment by blakerouse** [comment]
Anything can be a dictionary key if its hashable. The hash key for `Machine` should be the `system_id`.

**Comment by allenap** [comment]
My thoughts:

* Don't expose a _get-power-parameters-for-all-machines_ operation. It's not clear we need it now.

* I remain reluctant to embrace the _partially-loaded-object_ pattern, e.g. where a `Machine` instance knows only its `system_id` and the remaining attributes must be vivified by a call to `.load()`. That's a longer discussion, but here I think we should avoid that pattern until we've had it.

* We could/should note in the docstrings that these methods remain "alpha" and may change once we model BMCs as first class objects.

Hence I suggest something fairly minimal:

```python
Machines.get_power_parameters_for([...])  # --> {system_id: {dict-of-parameters}, ...}
Machine.get_power_parameters()  # --> {dict-of-parameters}
```

**Comment by brendan-donegan** [comment]
One last thing that's not 100% clear for me - should calling get_power_parameters_for() with no arguments (or indeed an empty list), return all power parameters, as a sort of 'easter egg'. Otherwise I'll need to write some code to 'defend' against calling it that way.

**Comment by allenap** [comment]
Let's say:

```python
get_power_parameters_for()  # --> TypeError
get_power_parameters_for([])  # --> {}
```

The `TypeError` comes from Python when a mandatory argument is not supplied; it doesn't need to be raised explicitly.

**Comment by blakerouse** [comment]
@allenap - I think avoiding the pattern is not a good idea. When we present this in the library I think we should strive to make it the way we want it to be. So we need to come to a decision on that pattern very soon. Without that pattern or another pattern that we determine, we have no nested objects. MAAS has lots of nested objects.
