### ISSUE TITLE
VLAN endpoint for MAAS CI

### ISSUE THREAD

**Issue by brendan-donegan** [maas/python-libmaas#89]
We want to be able to use the VLAN endpoint in the MAAS CI. The required operations are:

- Update a specified VLAN
- Delete a specified VLAN

**Comment by blakerouse** [comment]
With VLAN's being nested under Fabric's it would be best to use the nested objects specification that we designed for this:

```
# Get the default VLAN on the default fabric.
default_fabric = await client.fabrics.get(0)
default_vlan = await default_fabric.get_default_vlan()

# Get the all VLANs for the default fabric.
all_vlans = default_fabric.vlans
for vlan in all_vlans:
    if not vlan.loaded:
        await vlan.load()
```

**Comment by brendan-donegan** [comment]
We actually only **need** to be able to create and update a VLAN for this issue, but we may address reading as well.

Just to clarify, are you saying that VLANs should only be accessible through the fabrics endpoint and there should be no way to get all VLANs regardless of the Fabric they are on?

As an observation as well, I think fabrics.get(0) should be mapped to fabrics.get_default(). Knowing that '0' is the default is too much like magic

**Comment by blakerouse** [comment]
Yes all VLAN's are nested under fabric's. This is how the API works today.

`maas session vlans read {fabric_id}`

Very true `get_default()` is much better.

**Comment by blakerouse** [comment]
This was done in #110.
