### ISSUE TITLE
orign.xxxx problems - NameError: name 'origin' is not defined

### ISSUE THREAD

**Issue by Jgerardopine** [maas/python-libmaas#90]
Hi team,

  There seems to be problems with viscera and bones. We can list users, machines and devices with no problem, but when I try to get the version we get the following:

`nexius@ubuntu:~$ maas shell`
`Welcome to the MAAS shell.`
`Predefined objects:`
` client:`
`    A pre-canned client for 'rootpro'.`
`In [1]: origin.Version.read()`
`---------------------------------------------------------------------------`
`NameError                                 Traceback (most recent call last)`
`<ipython-input-1-22b2f32223e9> in <module>()`
`----> 1 origin.Version.read()`
`NameError: name 'origin' is not defined`

We followed carefully the instructions in the guide. So we logged in again but we only get the 

> A pre-canned client for 'rootpro'.

but never the:

> Predefined variables:
> origin: A `viscera` origin, configured for foo.
> session: A `bones` session, configured for foo.

I tried also to get logged in programmatically and we get the same result (with bones and viscera):

Viscera:
`In [2]: profile, origin = Origin.login("http://maas-rc-vm:5240/MAAS/api/2.0/", username="xxx",password="xxx")`
`---------------------------------------------------------------------------`
`NameError                                 Traceback (most recent call last)`
`<ipython-input-2-476daac84867> in <module>()
----> 1 profile, origin = Origin.login("http://maas-rc-vm:5240/MAAS/api/2.0/", username="xxx",password="xxx")`
`NameError: name 'Origin' is not defined`

Bones:
`In [3]:  profile, session = bones.SessionAPI.login("http://maas-rc-vm:5240/MAAS/api/2.0/", username="root",password="nexlan13")`
`---------------------------------------------------------------------------`
`NameError                                 Traceback (most recent call last)`
`<ipython-input-3-f5899c9dc824> in <module>()
----> 1 profile, session = bones.SessionAPI.login("http://maas-rc-vm:5240/MAAS/api/2.0/", username="xxx",password="xxx")`
`NameError: name 'bones' is not defined`

We installed it via PyPI (pip install python-libmaas) and we have the latest version. This is what was installed with pip:

>Requirement already up-to-date: python-libmaas in /usr/local/lib/python3.5/dist-packages
>Requirement already up-to-date: terminaltables>=2.1.0 in /usr/local/lib/python3.5/dist-packages (from python-libmaas)
>Requirement already up-to-date: beautifulsoup4>=4.4.1 in /usr/local/lib/python3.5/dist-packages (from python-libmaas)
>Requirement already up-to-date: oauthlib>=1.0.3 in /usr/local/lib/python3.5/dist-packages (from python-libmaas)
>Requirement already up-to-date: aiohttp>=1.1.4 in /usr/local/lib/python3.5/dist-packages (from python-libmaas)
>Requirement already up-to-date: colorclass>=1.2.0 in /usr/local/lib/python3.5/dist-packages (from python-libmaas)
>Requirement already up-to-date: PyYAML>=3.11 in /usr/local/lib/python3.5/dist-packages (from python-libmaas)
>Requirement already up-to-date: pytz>=2014.10 in /usr/local/lib/python3.5/dist-packages (from python-libmaas)
>Requirement already up-to-date: argcomplete>=1.0 in /usr/local/lib/python3.5/dist-packages (from python-libmaas)
>Requirement already up-to-date: async-timeout>=1.1.0 in /usr/local/lib/python3.5/dist-packages (from aiohttp>=1.1.4->python-libmaas)
>Requirement already up-to-date: multidict>=2.1.4 in /usr/local/lib/python3.5/dist-packages (from aiohttp>=1.1.4->python-libmaas)
>Requirement already up-to-date: yarl<0.10,>=0.9.8 in /usr/local/lib/python3.5/dist-packages (from aiohttp>=1.1.4->python-libmaas)
>Requirement already up-to-date: chardet in /usr/lib/python3/dist-packages (from aiohttp>=1.1.4-python-libmaas)

Could it be possible that libmaas is not complete? Which libraries should we have for this to work?

**Comment by allenap** [comment]
The `origin` and `session` objects from the interactive shell environment are no longer created by default; `client` is the default entry point now. However, you can get them back with extra command-line arguments:

For the viscera `origin`:

```console
$ maas shell --viscera
Welcome to the MAAS shell.

Predefined objects:

  client:
    A pre-canned client for 'a-profile-name'.

  origin:
    A pre-canned `viscera` origin for 'a-profile-name'.

```

For the bones `session`:

```console
$ maas shell --bones
Welcome to the MAAS shell.

Predefined objects:

  client:
    A pre-canned client for 'a-profile-name'.

  session:
    A pre-canned `bones` session for 'a-profile-name'.

```

Or both:

```console
$ maas shell --viscera --bones
Welcome to the MAAS shell.

Predefined objects:

  client:
    A pre-canned client for 'a-profile-name'.

  origin:
    A pre-canned `viscera` origin for 'a-profile-name'.

  session:
    A pre-canned `bones` session for 'a-profile-name'.

```
